/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

#import <MediaRemote/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (MRMediaRemoteAdditions)
- (BOOL)MR_isEqualToDictionary:(id)dictionary;	// 0x229d
@end
