/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DACardDAV.framework/DACardDAV
 */

#import <DACardDAV/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (CardDAVExtensions)
- (void)addObjectsAndKeys:(id)keys;	// 0x12e9
@end

@interface XXUnknownSuperclass (CardDAVExtensions)
- (id)prettyStringForDisplayName;	// 0x1335
@end

@interface XXUnknownSuperclass (CardDAVExtension)
- (BOOL)isCardDAVAccount;	// 0x2c81
@end

@interface XXUnknownSuperclass (CardDAVChildExtension)
- (BOOL)isCardDAVChildAccount;	// 0x32f9
@end
