/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

#import <TextInput/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (TIUserDictionaryWord)
- (BOOL)containsCJKVCharacters;	// 0x30dea9
- (BOOL)containsHiraganaKatakanaOrBopomofo;	// 0x30e051
- (BOOL)containsEmoji;	// 0x30e0cd
@end
