/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SoftwareUpdateServices.framework/SoftwareUpdateServices
 */

#import <SoftwareUpdateServices/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (SU)
- (id)safeObjectForKey:(id)key ofClass:(Class)aClass;	// 0x167c9
@end

@interface XXUnknownSuperclass (SU)
- (void)setSafeObject:(id)object forKey:(id)key;	// 0x16809
@end

@interface XXUnknownSuperclass (SU)
+ (id)sendSynchronousRequest:(id)request allowRedirects:(BOOL)redirects returningResponse:(id *)response error:(id *)error;	// 0x16ee5
@end
