/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SportsWorkout.framework/SportsWorkout
 */

#import <SportsWorkout/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (SportsWorkoutAdditions)
+ (id)two;	// 0x8799
@end
