/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DADaemonSupport.framework/DADaemonSupport
 */

#import <DADaemonSupport/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (DaemonAdditions)
- (void)deviceDidWake;	// 0x1861
- (void)deviceWillSleep;	// 0x185d
@end

@interface XXUnknownSuperclass (DAAgent)
- (Class)agentClass;	// 0x1b41
@end
