/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/IMAVCore.framework/IMAVCore
 */

#import <IMAVCore/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (AVChatExtensions)
@property(readonly, assign, nonatomic) BOOL hasNoConferencingCaps;	// G=0xc621; 
// declared property getter: - (BOOL)hasNoConferencingCaps;	// 0xc621
@end

@interface XXUnknownSuperclass (IMAVChatExtensions)
- (id)componentsJoinedIntoListWithMaxItems:(int)maxItems;	// 0x24b71
@end
