/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Preferences/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (PreferencesAdditions)
- (id)specifierForID:(id)anId;	// 0x9371
@end
