/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DALDAP.framework/DALDAP
 */

#import <DALDAP/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (LDAPExtensions)
- (id)ldapSanitizedAddress;	// 0x6571
- (id)humanReadableStringFromSearchBase;	// 0x6371
@end
