/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/IMCore.framework/Frameworks/IMDAppleServices.framework/IMDAppleServices
 */

// iOSOpenDev: wrapped with define check (since occurs in other dumped files)
#ifndef __NACContextOpaque_Ref__
#define __NACContextOpaque_Ref__ 1
typedef struct NACContextOpaque_ *NACContextOpaque_Ref;
#endif

// iOSOpenDev: wrapped with define check (since occurs in other dumped files)
#ifndef __CTServerConnectionRef__
#define __CTServerConnectionRef__ 1
typedef struct __CTServerConnection *CTServerConnectionRef;
#endif

typedef struct __SecKeyDescriptor SecKeyDescriptor;
typedef struct __SecKey {
	CFRuntimeBase _field1;
	SecKeyDescriptor *_field2;
	void *_field3;
} SecKey;

typedef struct _SecMPFullIdentity SecMPFullIdentity;

struct __SecKeyDescriptor;


