/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Stocks.framework/Stocks
 */

#import <Stocks/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (StockExtensions)
- (id)_stocksTrimmedString;	// 0xb49d
@end
