/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

#import <TelephonyUI/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (TelephonyUIInternal)
+ (id)tpImageNamed:(id)named inBundle:(id)bundle;	// 0x8de5
@end

@interface XXUnknownSuperclass (QueryParameterSupport)
- (id)asQueryParameterString;	// 0x10675
@end

@interface XXUnknownSuperclass (QueryParameters)
- (id)queryParameters;	// 0x107f1
- (id)URLWithNewQueryParameterDictionary:(id)newQueryParameterDictionary;	// 0x109d5
- (id)URLBySettingQueryParameterValue:(id)value forKey:(id)key;	// 0x1058d
- (id)URLByDeletingQueryParameterWithKey:(id)key;	// 0x10605
@end

@interface XXUnknownSuperclass (NSURL_TelephonyAdditions)
- (id)formattedPhoneNumber;	// 0x13369
- (id)numberQualifiedForAddressBook;	// 0x1342d
@end
