/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DAIMAPNotes.framework/DAIMAPNotes
 */

#import <DAIMAPNotes/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (IMAPNotesExtension)
- (BOOL)isIMAPNotesAccount;	// 0x16ed
@end
