/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/VisualAlert.framework/VisualAlert
 */

#import <VisualAlert/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (UIAccessibilityVisualAlertSafeCategory)
- (id)_safeValueForKey:(id)key;	// 0x16d5
@end
