/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ActorKit.framework/ActorKit
 */

#import <ActorKit/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (NSInvocationAdditions)
- (void)addInvocation:(id)invocation;	// 0x13a9
@end

@interface XXUnknownSuperclass (NSInvocationAdditions)
- (id)withProtocol:(id)protocol;	// 0x135d
@end
