/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MobileBackup.framework/MobileBackup
 */

#import <MobileBackup/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (MobileBackup)
- (void)shuffle;	// 0xadc9
@end

@interface XXUnknownSuperclass (MobileBackup)
+ (id)stringWithFileSystemRepresentation:(const char *)fileSystemRepresentation;	// 0xad81
+ (id)stringWithFileSystemRepresentation:(const char *)fileSystemRepresentation length:(unsigned)length;	// 0xa5e9
- (id)stringByAppendingSlash;	// 0xa5a1
- (id)MBAppendGreenteaSuffix;	// 0xaa19
@end
