/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/AXRuntime.framework/AXRuntime
 */

#import <AXRuntime/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (AXAttributedStringAdditions)
- (BOOL)isAXAttributedString;	// 0xa9d1
@end
