/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <YouTube/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (YTExtensions)
- (id)newYouTubeVideoDescription;	// 0x1a49
- (id)escapedYouTubeSearchString;	// 0x1b69
- (id)youTubeTrimmedString;	// 0x1ab5
- (id)stringByRemovingLTGT;	// 0x1b29
@end

@interface XXUnknownSuperclass (YTBase64)
- (id)decodedWebSafeBase64Data;	// 0x30b1
@end

@interface XXUnknownSuperclass (YTBase64)
- (id)webSafeBase64Data;	// 0x2ff5
@end

@interface XXUnknownSuperclass (Protection)
- (BOOL)writeToProtectedFile:(id)protectedFile atomically:(BOOL)atomically;	// 0x19241
@end
