/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/AppStoreUI.framework/AppStoreUI
 */

#import <AppStoreUI/AppStoreUI-Structs.h>
#import <AppStoreUI/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (ASAdditions)
- (int)applicationStoreURLType;	// 0x182d9
@end

@interface XXUnknownSuperclass (ASAdditions)
- (void)setText:(id)text forDisplayInBounds:(CGRect)bounds;	// 0x18505
- (id)initNoContentLabelWithText:(id)text bounds:(CGRect)bounds;	// 0x18391
@end
