/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SyncedDefaults.framework/SyncedDefaults
 */

#import <SyncedDefaults/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (SYDDebug)
- (void)_printDebugDescription;	// 0x4469
@end
