/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/RemoteUI.framework/RemoteUI
 */

#import <RemoteUI/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (RemoteUIAdditions)
+ (id)_remoteUI_colorWithString:(id)string;	// 0xc395
@end
