/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

#import <AppleAccount/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (SHA1Hashing)
- (id)SHA1Hash;	// 0xae79
@end
