/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/IMCore.framework/Frameworks/IMDaemonCore.framework/IMDaemonCore
 */

typedef struct _FZChatRoomValidity {
	int _field1;
	unsigned short _field2;
} FZChatRoomValidity;

typedef struct {
	CFRuntimeBase _field1;
	int _field2;
	int _field3;
} XXStruct_l7ui9B;

typedef struct __IMDMadridAttachmentRecord *IMDMadridAttachmentRecordRef;


