/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DASubCal.framework/DASubCal
 */

#import <DASubCal/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (SubCalValidity)
- (BOOL)isSubCalAuthError;	// 0x3145
@end

@interface XXUnknownSuperclass (SubCalUtilities)
- (BOOL)isSubCalURLString;	// 0x33d9
@end

@interface XXUnknownSuperclass (SubCalDigest)
- (id)digestForSubCal;	// 0x34fd
@end

@interface XXUnknownSuperclass (SubCalDigest)
- (id)modTagForSubCal;	// 0x3569
@end

@interface XXUnknownSuperclass (SubCalTaskReachabilityError)
- (BOOL)isSubCalReachabilityError;	// 0x35e9
@end
