/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ProtocolBuffer.framework/ProtocolBuffer
 */

#import <ProtocolBuffer/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (PBExtensions)
- (void)setObject:(id)object atIndex:(int)index;	// 0x5ea5
@end
