/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import <WebCore/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (WebCoreThreadAdditions)
- (void)releaseOnMainThread;	// 0x1cd399
@end
