/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DABookmarkDAV.framework/DABookmarkDAV
 */

#import <DABookmarkDAV/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (BookmarkDAVExtension)
- (BOOL)isBookmarkDAVAccount;	// 0x2905
@end

@interface XXUnknownSuperclass (BookmarkDAVChildExtension)
- (BOOL)isBookmarkDAVChildAccount;	// 0x2f25
@end
