/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SMSCTServer.framework/SMSCTServer
 */

#import <SMSCTServer/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (SMILInterpretation)
- (id)smilString;	// 0x8145
- (id)sortedPartsFromSMIL;	// 0x7be9
@end
