/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

#import <ImageCapture/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (ImageCaptureAdditions)
- (void)addItemsMatchingType:(id)type fromFolder:(id)folder;	// 0xb681
- (void)addItemsMatchingExtensions:(id)extensions orTypes:(id)types fromFolder:(id)folder;	// 0xb831
@end
