/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/GameKitServices.framework/Frameworks/AVConference.framework/AVConference
 */

#import <AVConference/XXUnknownSuperclass.h>


@interface XXUnknownSuperclass (AVConferenceError)
+ (id)AVConferenceServiceError:(int)error detailedCode:(int)code filePath:(id)path description:(id)description hResult:(long)result;	// 0x8f5dd
+ (id)AVConferenceServiceError:(int)error detailedCode:(int)code filePath:(id)path description:(id)description reason:(id)reason;	// 0x8f6cd
+ (id)AVConferenceServiceError:(int)error detailCode:(int)code description:(id)description;	// 0x8f78d
@end
